import { Trip, WishlistDestination } from "@/types";

export const MOCK_TRIPS: Trip[] = [
  {
    id: "trip-1",
    userId: "user-1",
    title: "Japan Family Trip",
    startDate: "2024-12-15",
    endDate: "2024-12-28",
    tripType: "family",
    primaryCountry: "Japan",
    summary:
      "A magical winter family trip through Tokyo, Kyoto and Osaka, filled with temple visits, ramen shops, Christmas lights and slow walks through old streets.",
    totalCost: 8500,
    currency: "USD",
    companions: ["Mom", "Dad", "Sister"],
    places: [
      {
        id: "place-1",
        tripId: "trip-1",
        name: "Shinjuku",
        country: "Japan",
        city: "Tokyo",
        latitude: 35.6938,
        longitude: 139.7036,
        visitDate: "2024-12-15",
        orderIndex: 0,
      },
      {
        id: "place-2",
        tripId: "trip-1",
        name: "Senso-ji Temple",
        country: "Japan",
        city: "Tokyo",
        latitude: 35.7148,
        longitude: 139.7967,
        visitDate: "2024-12-16",
        orderIndex: 1,
      },
      {
        id: "place-3",
        tripId: "trip-1",
        name: "Fushimi Inari",
        country: "Japan",
        city: "Kyoto",
        latitude: 34.9671,
        longitude: 135.7727,
        visitDate: "2024-12-20",
        orderIndex: 2,
      },
      {
        id: "place-4",
        tripId: "trip-1",
        name: "Dotonbori",
        country: "Japan",
        city: "Osaka",
        latitude: 34.6687,
        longitude: 135.5013,
        visitDate: "2024-12-24",
        orderIndex: 3,
      },
    ],
    media: [
      {
        id: "media-1",
        tripId: "trip-1",
        source: "manual_upload",
        fileUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400",
        mediaType: "photo",
        takenAt: "2024-12-16",
        caption: "Senso-ji at dawn",
        peopleTags: [],
      },
      {
        id: "media-2",
        tripId: "trip-1",
        source: "manual_upload",
        fileUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400",
        mediaType: "photo",
        takenAt: "2024-12-20",
        caption: "The thousand torii gates",
        peopleTags: ["Mom", "Dad"],
      },
      {
        id: "media-3",
        tripId: "trip-1",
        source: "manual_upload",
        fileUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400",
        mediaType: "photo",
        takenAt: "2024-12-22",
        caption: "Kyoto bamboo grove",
        peopleTags: [],
      },
    ],
    itineraryItems: [
      {
        id: "it-1",
        tripId: "trip-1",
        date: "2024-12-15",
        title: "Arrive in Tokyo",
        description: "Flew into Narita. Checked into hotel in Shinjuku. Explored the area.",
        transportMode: "flight",
      },
      {
        id: "it-2",
        tripId: "trip-1",
        date: "2024-12-16",
        title: "Asakusa & Senso-ji",
        description: "Visited Senso-ji Temple, Tokyo Skytree, had tempura lunch.",
        transportMode: "walk",
      },
      {
        id: "it-3",
        tripId: "trip-1",
        date: "2024-12-19",
        title: "Shinkansen to Kyoto",
        description: "Bullet train to Kyoto. Arrived and checked in. Evening walk in Gion.",
        transportMode: "train",
      },
      {
        id: "it-4",
        tripId: "trip-1",
        date: "2024-12-20",
        title: "Fushimi Inari & Arashiyama",
        description: "Early morning at Fushimi Inari, then bamboo grove at Arashiyama.",
        transportMode: "walk",
      },
    ],
    costItems: [
      { id: "c-1", tripId: "trip-1", category: "flights", description: "Return flights x4", amount: 3200, currency: "USD" },
      { id: "c-2", tripId: "trip-1", category: "hotels", description: "13 nights accommodation", amount: 2600, currency: "USD" },
      { id: "c-3", tripId: "trip-1", category: "food", description: "Food & dining", amount: 1200, currency: "USD" },
      { id: "c-4", tripId: "trip-1", category: "transport", description: "JR Pass x4", amount: 800, currency: "USD" },
      { id: "c-5", tripId: "trip-1", category: "attractions", description: "Entrance fees & activities", amount: 400, currency: "USD" },
      { id: "c-6", tripId: "trip-1", category: "shopping", description: "Souvenirs & shopping", amount: 300, currency: "USD" },
    ],
  },
  {
    id: "trip-2",
    userId: "user-1",
    title: "Solo Backpack Through Southeast Asia",
    startDate: "2023-06-01",
    endDate: "2023-06-30",
    tripType: "solo",
    primaryCountry: "Thailand",
    summary: "A month-long solo adventure across Thailand, Vietnam and Cambodia. Street food, temples, beaches and beautiful chaos.",
    totalCost: 3200,
    currency: "USD",
    companions: [],
    places: [
      {
        id: "place-5",
        tripId: "trip-2",
        name: "Khao San Road",
        country: "Thailand",
        city: "Bangkok",
        latitude: 13.7583,
        longitude: 100.4975,
        visitDate: "2023-06-01",
        orderIndex: 0,
      },
      {
        id: "place-6",
        tripId: "trip-2",
        name: "Old Quarter",
        country: "Vietnam",
        city: "Hanoi",
        latitude: 21.0285,
        longitude: 105.8542,
        visitDate: "2023-06-12",
        orderIndex: 1,
      },
      {
        id: "place-7",
        tripId: "trip-2",
        name: "Angkor Wat",
        country: "Cambodia",
        city: "Siem Reap",
        latitude: 13.4125,
        longitude: 103.8670,
        visitDate: "2023-06-22",
        orderIndex: 2,
      },
    ],
    media: [
      {
        id: "media-4",
        tripId: "trip-2",
        source: "manual_upload",
        fileUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=400",
        mediaType: "photo",
        takenAt: "2023-06-22",
        caption: "Sunrise at Angkor Wat",
        peopleTags: [],
      },
    ],
    itineraryItems: [
      {
        id: "it-5",
        tripId: "trip-2",
        date: "2023-06-01",
        title: "Arrived in Bangkok",
        description: "Street food crawl on Khao San Road.",
        transportMode: "flight",
      },
    ],
    costItems: [
      { id: "c-7", tripId: "trip-2", category: "flights", description: "Flights", amount: 900, currency: "USD" },
      { id: "c-8", tripId: "trip-2", category: "hotels", description: "Hostels & guesthouses", amount: 600, currency: "USD" },
      { id: "c-9", tripId: "trip-2", category: "food", description: "Street food & restaurants", amount: 500, currency: "USD" },
      { id: "c-10", tripId: "trip-2", category: "transport", description: "Buses & trains", amount: 400, currency: "USD" },
      { id: "c-11", tripId: "trip-2", category: "attractions", description: "Entry fees", amount: 300, currency: "USD" },
      { id: "c-12", tripId: "trip-2", category: "other", description: "Visa & misc", amount: 500, currency: "USD" },
    ],
  },
  {
    id: "trip-3",
    userId: "user-1",
    title: "Paris with My Love",
    startDate: "2024-02-10",
    endDate: "2024-02-16",
    tripType: "special_someone",
    primaryCountry: "France",
    summary: "A romantic Valentine's week in Paris. The Eiffel Tower, Montmartre, Seine river cruise and too many croissants.",
    totalCost: 4200,
    currency: "USD",
    companions: ["Sarah"],
    places: [
      {
        id: "place-8",
        tripId: "trip-3",
        name: "Eiffel Tower",
        country: "France",
        city: "Paris",
        latitude: 48.8584,
        longitude: 2.2945,
        visitDate: "2024-02-11",
        orderIndex: 0,
      },
      {
        id: "place-9",
        tripId: "trip-3",
        name: "Montmartre",
        country: "France",
        city: "Paris",
        latitude: 48.8867,
        longitude: 2.3431,
        visitDate: "2024-02-13",
        orderIndex: 1,
      },
    ],
    media: [
      {
        id: "media-5",
        tripId: "trip-3",
        source: "manual_upload",
        fileUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400",
        mediaType: "photo",
        takenAt: "2024-02-14",
        caption: "Valentine's Day in Paris",
        peopleTags: ["Sarah"],
      },
    ],
    itineraryItems: [],
    costItems: [
      { id: "c-13", tripId: "trip-3", category: "flights", description: "Flights x2", amount: 1200, currency: "USD" },
      { id: "c-14", tripId: "trip-3", category: "hotels", description: "6 nights boutique hotel", amount: 1800, currency: "USD" },
      { id: "c-15", tripId: "trip-3", category: "food", description: "Dining & cafes", amount: 800, currency: "USD" },
      { id: "c-16", tripId: "trip-3", category: "attractions", description: "Museum & tours", amount: 400, currency: "USD" },
    ],
  },
  {
    id: "trip-4",
    userId: "user-1",
    title: "Bali with the Squad",
    startDate: "2023-12-20",
    endDate: "2023-12-31",
    tripType: "friends",
    primaryCountry: "Indonesia",
    summary: "New Year's in Bali with six friends. Temples, rice terraces, surf lessons and a rooftop countdown.",
    totalCost: 2800,
    currency: "USD",
    companions: ["Alex", "James", "Maria", "Tom", "Priya"],
    places: [
      {
        id: "place-10",
        tripId: "trip-4",
        name: "Seminyak Beach",
        country: "Indonesia",
        city: "Bali",
        latitude: -8.6911,
        longitude: 115.1668,
        visitDate: "2023-12-20",
        orderIndex: 0,
      },
      {
        id: "place-11",
        tripId: "trip-4",
        name: "Tegallalang Rice Terrace",
        country: "Indonesia",
        city: "Ubud",
        latitude: -8.4312,
        longitude: 115.2781,
        visitDate: "2023-12-24",
        orderIndex: 1,
      },
    ],
    media: [
      {
        id: "media-6",
        tripId: "trip-4",
        source: "manual_upload",
        fileUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
        thumbnailUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400",
        mediaType: "photo",
        takenAt: "2023-12-24",
        caption: "Rice terraces at golden hour",
        peopleTags: ["Alex", "James"],
      },
    ],
    itineraryItems: [],
    costItems: [
      { id: "c-17", tripId: "trip-4", category: "flights", description: "Flights", amount: 800, currency: "USD" },
      { id: "c-18", tripId: "trip-4", category: "hotels", description: "Villa rental (split 6 ways)", amount: 1000, currency: "USD" },
      { id: "c-19", tripId: "trip-4", category: "food", description: "Food & drinks", amount: 600, currency: "USD" },
      { id: "c-20", tripId: "trip-4", category: "attractions", description: "Activities", amount: 400, currency: "USD" },
    ],
  },
];

export const MOCK_WISHLIST: WishlistDestination[] = [
  {
    id: "wish-1",
    userId: "user-1",
    destinationCity: "Santorini",
    destinationCountry: "Greece",
    originCity: "Singapore",
    preferredStartDate: "2025-08-01",
    preferredEndDate: "2025-08-14",
    cabinClass: "economy",
    maxPrice: 1200,
    currency: "USD",
    notes: "Dream summer destination",
    alertEnabled: true,
  },
  {
    id: "wish-2",
    userId: "user-1",
    destinationCity: "New York",
    destinationCountry: "USA",
    originCity: "Singapore",
    cabinClass: "economy",
    maxPrice: 900,
    currency: "USD",
    alertEnabled: true,
  },
  {
    id: "wish-3",
    userId: "user-1",
    destinationCity: "Cape Town",
    destinationCountry: "South Africa",
    originCity: "Singapore",
    cabinClass: "economy",
    maxPrice: 1500,
    currency: "USD",
    notes: "Would love to do a safari nearby",
    alertEnabled: false,
  },
];
